# C++11 多线程编程注意点

## 线程构造时传递引用类型的参数



下面代码所示  fctor 需要一个引用类型的参数 msg



```c++
class Fctor {
public:
	void operator()(std::string& msg) {
		std::cout << "from t1 " << msg << std::endl;
		msg = "123";
	}
};

int main()
{
	std::string str = "456";
	std::thread t(Fctor(), str);

	t.join();

	std::cout << str << std::endl;
}

```



这段代码有两种可能：

1. 编译器报错 因为 fctor 需要传递引用 所以  “std::invoke”: 未找到匹配的重载函数 
2. 编译成功 但 str的值没有被修改成123  输出456 和 456



解决问题： 使用std::ref包裹参数str  

```c++
int main()
{
	std::string str = "456";
	std::thread t(Fctor(), std::ref(str));
	t.join();

	std::cout << str << std::endl;
}
```

如果主线程不在使用 str 就不必要考虑线程间的资源竞争问题了
可以使用std::move 移动资源到子线程

```c++
int main()
{
	std::string str = "456";
	std::thread t(Fctor(), std::move(str));
	t.join();
}

```

## cpu 个数

```c++
std::thread::hardware_concurrency();
```



## RAII 解锁方式

```c++
std::mutex mu;
{
    std::lock_guard<std::mutex> guard(mu);
}

```

```c++
std::mutex mu;
{
    std::lock_guard<std::mutex> guard(mu);
}
```



### RAII 也会造成死锁 如下 

如果t1执行到mu2前 主线程已经拿到了mu2的，那么t1会等待mu2

但主线程要继续执行就需要mu 而这里是永远拿不到mu的，所以发生了死锁

正确方法是mu 和 mu2的上锁顺序要相同。或者使用std::lock使用正确的顺序传入

```c++
void func1(){
	std::lock_guard<std::mutex> guard1(mu);
  std::lock_guard<std::mutex> guard2(mu2);
}
void func2(){
  	std::lock_guard<std::mutex> guard2(mu2);
  	std::lock_guard<std::mutex> guard1(mu);
}

int main(){
  std::thread t1(func1);
  func2();
  return 0;
}

//正确方法1
void func1(){
	std::lock_guard<std::mutex> guard1(mu);
  std::lock_guard<std::mutex> guard2(mu2);
}
void func2(){
  std::lock_guard<std::mutex> guard1(mu);
  std::lock_guard<std::mutex> guard2(mu2);
}

//正确方法2
void func1(){
	std::lock(mu,mu2);
  	std::lock_guard<std::mutex> guard1(mu,std::adopt_lock);
  std::lock_guard<std::mutex> guard2(mu2,std::adopt_lock);
}
void func2(){
  	std::lock(mu,mu2); //此后顺序可以乱
    std::lock_guard<std::mutex> guard2(mu2,std::adopt_lock); //仅仅是获取所有权
  	std::lock_guard<std::mutex> guard1(mu,std::adopt_lock);
}

```



### unique_lock

**注意：unique_lock 和 lock_guard都不能被拷贝.   unique_lock可以被移动。lock_guard不能被移动**

Unique_lock移动后 使用权可以转移

lock_guard 的性能高于 unique_lock

```c++
void func(){

  	std::unique_lock<std::mutex> locker(mu,std::defer_lock);
  
  	//... 不需要锁的代码	
  	locker.lock();
  	//..需要锁的代码
  	locker.unlock();
  	
  
  	std::unique_lock<std::mutex> locker2 = std::move(locker);
}
```



## 确保一个函数只被一个线程调用一次 std::once_flag



```c++
std::once_flag m_flag;
void openfile(std::string path){
//里面的lambda表达式只会被一个线程执行一次
	std::call_once(m_flag,[&](){
		f.open(path.c_str());
	});
}
```





## future

有一段程序输出 n的阶乘 创建一个线程 去计算

```c++

void factorial(int n){
    int res = 1;
    for (int i = 1; i <= n; ++i) {
        res *= i;
    }

}

int main() {
    std::thread t1(factorial,4);

    t1.join();
    return 0;
}	
```



如果想吧t1线程执行的结果传递到父线程 就必须传入一个ret的引用进去，所以此时就产生了线程之间的对同一内存的共享。所以要加上`mutex` 和`condition` 保护同步这个ret变量，这个方式就显得非常麻烦。所以标准库为我们提供了`future库`来解决这个问题。





**注意：future 的get函数只能调用一次 如果调用两次就会崩溃**

如果第一个参数传入`std::launch::deferred `则会延期启动这个函数 并不会创建线程

如果传入`std::launch::async` 则会创建新的线程执行这个函数

```c++
#include <future>
int factorial(int n){
    int res = 1;
    for (int i = 1; i <= n; ++i) {
        res *= i;
    }
    return res;
}

int main() {
    int n = 0;
    //std::future<int> fu =  std::async(factorial,4);
  	//std::future<int> fu =  std::async(std::launch::deferred,factorial,4);
   	std::future<int> fu =  std::async(std::launch::async,factorial,4);
    n = fu.get(); //等待子线程结束 并获得返回结果
    return 0;
}
```



### 从子线程中获取主线程的变量

```c++
#include <thread>
#include <future>
#include <iostream>
int factorial(std::future<int>& f){
    std::cout << "in thread t1 "<< std::endl;
    int n = f.get();
    int res = 1;
    for (int i = 1; i <= n; ++i) {
        res *= i;
    }
    return res;
}

int main() {
    int n = 0;
    std::promise<int> p;
    std::future<int> f = p.get_future(); //从promise中获取future
    std::future<int> fu =  std::async(std::launch::async,factorial,std::ref(f));
    std::cout << "after async" << std::endl;
    p.set_value(4);//设置 f 的值为4
    n = fu.get();//创建线程并且返回执行结果

    std::cout << n << std::endl;
    return 0;
}

```



打印结果为：

```
after async
in thread t1 
24
```



**注意： 如果 在执行get前没有`set_value`那么在factorial函数中执行 `f.get();`会抛出异常 `std::future_errc::broken_promise`**

**注意：promise 和 future不能被拷贝 只能够move**

```c++
std::promise<int> p1;
std::promise<int> p2 = p1; //报错
std::promise<int> p2 = std::move(p1); //正确
```



### 多个线程共享一个future  shared_future

由于future的get只能被执行一次 所以如果有多次async执行的话会发生错误:

`Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`

```
    std::promise<int> p;
    std::future<int> f = p.get_future();
    std::future<int> fu1 =  std::async(std::launch::async,factorial,std::ref(f));
    std::future<int> fu2 =  std::async(std::launch::async,factorial,std::ref(f));
    std::future<int> fu3 =  std::async(std::launch::async,factorial,std::ref(f));
```



这种情况就要使用`shared_future` 由于`shared_future`可以被拷贝 所以可以直接值传递不会发生错误

```

```





